run:
  timeout: 5m
linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - gocheckcompilerdirectives
    - gofmt
    - gofumpt
    - gosec # Keep gosec enabled
    - gosimple
    - govet
    - ineffassign
    - intrange
    - makezero
    - misspell
    - nilerr
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - unconvert
    - usetesting
    - wastedassign
    - whitespace
  disable:
    - usestdlibvars
    - errcheck
linters-settings:
  staticcheck:
    checks:
      - all
      - -SA1019 # omit Deprecated check
issues:
  exclude-rules:
    # G107: Potential HTTP request made with variable URL
    - path: llm/server.go
      linters: [gosec]
      text: "G107"
    # G302: Use of os.Chmod is discouraged
    - path: server/layer.go
      linters: [gosec]
      text: "G302"
    # G404: Use of weak random number generator is acceptable for non-crypto purposes
    - path: server/internal/internal/backoff/backoff.go
      linters: [gosec]
      text: "G404"
    - path: openai/openai.go
      linters: [gosec]
      text: "G404"
    # G115: Integer overflow conversions are deemed safe in this context
    - path: fs/
      linters: [gosec]
      text: "G115"
    - path: convert/
      linters: [gosec]
      text: "G115"
    - path: api/types.go
      linters: [gosec]
      text: "G115"
    - path: model/
      linters: [gosec]
      text: "G115"
    - path: server/
      linters: [gosec]
      text: "G115"
    # G306: Expect WriteFile permissions to be 0600 or less
    - path: _test.go
      linters: [gosec]
      text: "G306"
    # G402: TLS MinVersion too low
    - path: server/internal/client/ollama/registry.go
      linters: [gosec]
      text: "G402"
    # G112: Potential Slowloris Attack
    - path: runner/
      linters: [gosec]
      text: "G112"
    - path: server/routes.go
      linters: [gosec]
      text: "G112"
    # G501 & G401: Use of MD5 is acceptable for file integrity checks
    - path: server/upload.go
      linters: [gosec]
      text: "G501"
    - path: server/upload.go
      linters: [gosec]
      text: "G401"

severity:
  default-severity: error
  rules:
    - linters:
        - gofmt
        - goimports
        - intrange
      severity: info